name: "Build"
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Building project
        run: echo "building project..."
      - id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Create release artifact
        run: |
          mkdir release
          cd release
          echo "dinamo" > dinamo.txt
          echo "$GITHUB_JOB" > job.txt
          echo "$GITHUB_SHA" > sha.txt
          cp ../README.md .
          tar --xform=s:'\./\?':: -czf ../artifact-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz ./
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: artifact-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz
          if-no-files-found: error
      - name: Delete artifact(s)
        run: |
          rm -r release
          rm artifact*.tar.gz
      - name: Debug
        run: ls -l
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
      - name: Debug
        run: ls -l
