on:
  workflow_run:
    workflows: ["Build"]
    branches: ["master"]
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    types:
      - completed

name: Release

jobs:
  release:
    if: (${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.ref, 'refs/tags/'))
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: build.yaml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conculsion::
          # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          # "completed", "in_progress", "queued"
          # Default: "completed"
          workflow_conclusion: success
          # Optional, will get head commit SHA
          # pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
          # commit: ${{github.event.pull_request.head.sha}}
          # Optional, will use the branch
          branch: master
          # Optional, will use specified workflow run
          # run_id: 1122334455
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: build-artifact
          # Optional, directory where to extract artifact
          path: ./
          # Optional, defaults to current repo
          # repo: ${{github.repository}}
      - name: Create release and upload artifact
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          files: artifact-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz
      - name: debug
        run: |
          ls -l
          mkdir dinamo
          tar zxvf artifact-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz -C dinamo
          ls -l dinamo
          cat dinamo/sha.txt
